site_name: 'OpenHisiIpCam'
site_url: 'http://openhisiipcam.org'
site_description: 'Open source network camera firmware for HiSilicon based hardware'
site_author: 'nikitos1550'


theme:
 name: 'material'
 language: 'en'
 palette:
   primary: 'pink'
   accent: 'pink'
 logo:
  icon: 'photo_camera'
 favicon: 'favicon.ico'

repo_name: 'GitHub'
repo_url: 'https://github.com/OpenHisiIpCam/OpenHisiIpCam'

edit_uri: ''

copyright: 'Copyright &copy; 2018 OpenHisiIpCam project'

extra:
 social:
  - type: 'github'
    link: 'https://github.com/OpenHisiIpCam'

nav:
 - 'Overview' : 'index.md'
 - 'About IP cameras' : 
      - 'How IP camera works' : 'cctv/how-ip-camera-works.md'
      - 'Chinese CCTV market' : 'cctv/chinese-cctv-market.md'
      - 'HiSilicon`s SoCs overview' : 'cctv/hisilicon-chips.md'
      - 'Hardware explained' : 'hardware/hardware-explained.md'
 - 'How-to articles' :
      - 'Low level UART debug' : 'how-to/uart-debug.md'
      - 'Deploy firmware' : 'how-to/deploy-firmware.md'
 - 'Known hardware' : 'hardware/known-hardware.md'
 - 'Goals' : 'goals.md'
 - 'Roadmap' : 'roadmap.md'
 - 'Contributing' : 'contributing.md'
