site_name: 'OpenHisiIpCam'
site_url: 'http://openhisiipcam.org'
site_description: 'Open source network camera firmware for HiSilicon based hardware'
site_author: 'nikitos1550'


theme:
 name: 'material'
 language: 'en'
 palette:
   primary: 'pink'
   accent: 'pink'
 logo:
  icon: 'photo_camera'

repo_name: 'GitHub'
repo_url: 'https://github.com/OpenHisiIpCam/OpenHisiIpCam'

edit_uri: ''

nav:
 - 'Overview' : 'index.md'
 - 'IP cameras' : 
      - 'How IP camera works' : 'cctv/how-ip-camera-works.md'
      - 'Chinese CCTV market' : 'cctv/chinese-cctv-market.md'
      - 'HiSilicon chips overview' : 'cctv/hisilicon-chips.md'
      - 'Hardware explained' : '...'
 - 'How to' :
      - 'Low level UART debug' : '../uart-debug.md'
      - 'Deploy firmware' : '...'
 - 'Known hardware' : '...'
 - 'Goals' : '...'
 - 'Roadmap' : '...'
 - 'Contributing' : '...'
