site_name: 'OpenHisiIpCam'
site_url: 'http://openhisiipcam.org'
site_description: 'Open source network camera firmware for HiSilicon based hardware'
site_author: 'nikitos1550'


theme:
 name: 'material'
 language: 'en'
 palette:
   primary: 'teal'
   accent: 'teal'
 logo:
  icon: 'photo_camera'
 favicon: 'favicon.ico'

#markdown_extensions:
#  - pymdownx.arithmatex
#  - pymdownx.betterem:
#      smart_enable: all
#  - pymdownx.caret
#  - pymdownx.critic
#  - pymdownx.details
#  - pymdownx.emoji:
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
#  - pymdownx.inlinehilite
#  - pymdownx.magiclink
#  - pymdownx.mark
#  - pymdownx.smartsymbols
#  - pymdownx.superfences
#  - pymdownx.tasklist:
#      custom_checkbox: true
#  - pymdownx.tilde

markdown_extensions:
  - admonition
  - pymdownx.emoji:
     emoji_generator: !!python/name:pymdownx.emoji.to_svg

repo_name: 'GitHub'
repo_url: 'https://github.com/OpenHisiIpCam/OpenHisiIpCam'

edit_uri: ''

copyright: 'Copyright &copy; 2018 OpenHisiIpCam project'

extra:
 social:
  - type: 'github'
    link: 'https://github.com/OpenHisiIpCam'

nav:
 - 'Project overview' : 'index.md'
 - 'About ip cameras' : 
      - 'What ip camera is' : 'cctv/what-ip-camera-is.md'
      - 'Chinese CCTV market' : 'cctv/chinese-cctv-market.md'
 - 'Hardware' :
      - 'HiSilicon`s SoCs overview' : 'hardware/hisilicon-chips.md'
      - 'Hardware explained' : 'hardware/hardware-explained.md'
      - 'Compatible hardware' : 'hardware/known-compatible-hardware.md'
 - 'Roadmap' : 'roadmap.md'
 - 'Contributing' : 'contributing.md'

 #- 'How-to articles' :
 #     - 'Low level UART debug' : 'how-to/uart-debug.md'
 #     - 'Deploy firmware' : 'how-to/deploy-firmware.md'


google_analytics: ['UA-125863149-1', 'openhisiipcam.org']
